use crate::{
    HandshakeError, HandshakeErrorKind, Identity, LinkCapabilities, PeerId, ProtocolCapabilitySet,
    ProtocolDebugIdentity, ProtocolStableId, ProtocolVersion, SchemaRef, SessionId, VersionRange,
};
use std::collections::BTreeSet;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProtocolOffer {
    pub stable_id: ProtocolStableId,
    pub debug_identity: Option<ProtocolDebugIdentity>,
    pub versions: VersionRange,
    pub schema: SchemaRef,
    pub capabilities: ProtocolCapabilitySet,
}

impl ProtocolOffer {
    pub fn from_debug_namespace(namespace: &str, versions: VersionRange) -> Self {
        let (authority, name) = namespace.rsplit_once('.').unwrap_or(("local", namespace));
        let debug_identity = ProtocolDebugIdentity::new(authority, name);
        let stable_id = debug_identity.stable_id();
        Self {
            stable_id,
            debug_identity: Some(debug_identity),
            versions,
            schema: SchemaRef::for_contract(authority, name, 1, namespace.as_bytes()),
            capabilities: ProtocolCapabilitySet::empty(stable_id),
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProtocolSelection {
    pub stable_id: ProtocolStableId,
    pub version: ProtocolVersion,
    pub schema: SchemaRef,
    pub capabilities: ProtocolCapabilitySet,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AuthPath {
    FirstPairing,
    TrustedReconnect,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct IdentityProof {
    /// Opaque bytes interpreted by an external identity verifier.
    pub opaque: Vec<u8>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum HandshakeFrame {
    Hello {
        identity: Identity,
        link_versions: VersionRange,
        link_capabilities: LinkCapabilities,
        protocols: Vec<ProtocolOffer>,
        requested_auth: AuthPath,
    },
    Challenge {
        responder: Identity,
        link_version: ProtocolVersion,
        link_capabilities: LinkCapabilities,
        auth_path: AuthPath,
        nonce: [u8; 32],
    },
    IdentityProof(IdentityProof),
    Selection {
        session_id: SessionId,
        protocols: Vec<ProtocolSelection>,
    },
    Confirm {
        session_id: SessionId,
    },
    Confirmed {
        session_id: SessionId,
    },
    Reject {
        kind: HandshakeErrorKind,
    },
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum HandshakeRole {
    Initiator,
    Responder,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum HandshakeState {
    Ready,
    AwaitingHello,
    AwaitingChallenge,
    AwaitingProof,
    AwaitingVerification,
    AwaitingSelection,
    AwaitingConfirmation,
    AwaitingConfirmed,
    Established,
    Failed,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct VerificationRequest {
    pub peer_id: PeerId,
    pub auth_path: AuthPath,
    pub nonce: [u8; 32],
    pub proof: IdentityProof,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProofDecision {
    Accept,
    Reject,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NegotiatedSession {
    pub session_id: SessionId,
    pub local: Identity,
    pub remote: Identity,
    pub link_version: ProtocolVersion,
    pub link_capabilities: LinkCapabilities,
    pub protocols: Vec<ProtocolSelection>,
    pub auth_path: AuthPath,
}

impl NegotiatedSession {
    /// The control identity rules are fixed by the authenticated handshake and
    /// must not be changed for the lifetime of this session.
    pub const fn control_identity_mode(&self) -> crate::ControlIdentityMode {
        crate::ControlIdentityMode::negotiate(self.link_capabilities)
    }

    pub const fn control_mode_guard(&self) -> crate::ControlModeGuard {
        crate::ControlModeGuard::new(self.control_identity_mode())
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum HandshakeOutput {
    Send(HandshakeFrame),
    VerifyIdentity(VerificationRequest),
    Established(NegotiatedSession),
}

#[derive(Clone, Debug)]
pub struct HandshakePolicy {
    pub link_versions: VersionRange,
    pub link_capabilities: LinkCapabilities,
    /// Full protocol catalog exposed only after an existing trust relationship.
    pub protocols: Vec<ProtocolOffer>,
    /// Minimal non-sensitive catalog available during first pairing.
    pub pairing_protocols: Vec<ProtocolOffer>,
    pub allow_pairing: bool,
    pub trusted_peers: BTreeSet<PeerId>,
    pub max_protocol_offers: usize,
    pub max_identity_proof_bytes: usize,
}

#[derive(Clone, Debug)]
pub struct HandshakeConfig {
    pub identity: Identity,
    pub policy: HandshakePolicy,
    /// Supplied by a cryptographically secure owner; core never generates entropy.
    pub challenge_nonce: [u8; 32],
    /// Opaque proof generated by an external identity provider.
    pub identity_proof: IdentityProof,
    /// Responder-owned fresh session identity.
    pub session_id: SessionId,
}

#[derive(Debug)]
pub struct HandshakeMachine {
    role: HandshakeRole,
    state: HandshakeState,
    config: HandshakeConfig,
    remote: Option<Identity>,
    auth_path: Option<AuthPath>,
    link_version: Option<ProtocolVersion>,
    link_capabilities: LinkCapabilities,
    selected_protocols: Vec<ProtocolSelection>,
    pending_verification: Option<VerificationRequest>,
}

impl HandshakeMachine {
    pub fn initiator(config: HandshakeConfig) -> Self {
        Self::new(HandshakeRole::Initiator, HandshakeState::Ready, config)
    }

    pub fn responder(config: HandshakeConfig) -> Self {
        Self::new(
            HandshakeRole::Responder,
            HandshakeState::AwaitingHello,
            config,
        )
    }

    fn new(role: HandshakeRole, state: HandshakeState, config: HandshakeConfig) -> Self {
        Self {
            role,
            state,
            config,
            remote: None,
            auth_path: None,
            link_version: None,
            link_capabilities: LinkCapabilities::default(),
            selected_protocols: Vec::new(),
            pending_verification: None,
        }
    }

    pub fn state(&self) -> HandshakeState {
        self.state
    }

    pub fn start(&mut self, auth_path: AuthPath) -> Result<HandshakeFrame, HandshakeError> {
        if self.role != HandshakeRole::Initiator || self.state != HandshakeState::Ready {
            return Err(self.fail(
                HandshakeErrorKind::UnexpectedMessage,
                "handshake cannot be started in the current state",
            ));
        }
        let protocols = match auth_path {
            AuthPath::FirstPairing => &self.config.policy.pairing_protocols,
            AuthPath::TrustedReconnect => &self.config.policy.protocols,
        };
        if protocols.len() > self.config.policy.max_protocol_offers {
            return Err(self.fail(
                HandshakeErrorKind::LimitExceeded,
                "too many local protocol offers",
            ));
        }
        if protocols.iter().any(|offer| {
            offer.schema.revision.0 == 0
                || offer.capabilities.protocol_id != offer.stable_id
                || !offer.capabilities.is_bounded()
                || offer
                    .debug_identity
                    .as_ref()
                    .is_some_and(|identity| identity.stable_id() != offer.stable_id)
        }) {
            return Err(self.fail(
                HandshakeErrorKind::ProtocolConflict,
                "upper protocol offer is internally inconsistent",
            ));
        }
        self.auth_path = Some(auth_path);
        self.state = HandshakeState::AwaitingChallenge;
        Ok(HandshakeFrame::Hello {
            identity: self.config.identity,
            link_versions: self.config.policy.link_versions,
            link_capabilities: self.config.policy.link_capabilities,
            protocols: protocols.clone(),
            requested_auth: auth_path,
        })
    }

    pub fn receive(
        &mut self,
        frame: HandshakeFrame,
    ) -> Result<Vec<HandshakeOutput>, HandshakeError> {
        match (self.role, self.state, frame) {
            (
                HandshakeRole::Responder,
                HandshakeState::AwaitingHello,
                HandshakeFrame::Hello {
                    identity,
                    link_versions,
                    link_capabilities,
                    protocols,
                    requested_auth,
                },
            ) => self.receive_hello(
                identity,
                link_versions,
                link_capabilities,
                protocols,
                requested_auth,
            ),
            (
                HandshakeRole::Initiator,
                HandshakeState::AwaitingChallenge,
                HandshakeFrame::Challenge {
                    responder,
                    link_version,
                    link_capabilities,
                    auth_path,
                    nonce: _,
                },
            ) => {
                if self
                    .config
                    .policy
                    .link_versions
                    .negotiate(VersionRange::new(link_version, link_version))
                    .is_none()
                    || self.auth_path != Some(auth_path)
                    || !link_capabilities.is_subset_of(self.config.policy.link_capabilities)
                {
                    return Err(self.fail(
                        HandshakeErrorKind::IncompatibleVersion,
                        "responder selected an incompatible handshake",
                    ));
                }
                self.remote = Some(responder);
                self.link_version = Some(link_version);
                self.link_capabilities = link_capabilities;
                self.state = HandshakeState::AwaitingSelection;
                Ok(vec![HandshakeOutput::Send(HandshakeFrame::IdentityProof(
                    self.config.identity_proof.clone(),
                ))])
            }
            (
                HandshakeRole::Responder,
                HandshakeState::AwaitingProof,
                HandshakeFrame::IdentityProof(proof),
            ) => {
                if proof.opaque.len() > self.config.policy.max_identity_proof_bytes {
                    return Err(self.fail(
                        HandshakeErrorKind::LimitExceeded,
                        "identity proof exceeds configured limit",
                    ));
                }
                let request = VerificationRequest {
                    peer_id: self.remote.expect("remote set after hello").peer_id,
                    auth_path: self.auth_path.expect("auth path set after hello"),
                    nonce: self.config.challenge_nonce,
                    proof,
                };
                self.pending_verification = Some(request.clone());
                self.state = HandshakeState::AwaitingVerification;
                Ok(vec![HandshakeOutput::VerifyIdentity(request)])
            }
            (
                HandshakeRole::Initiator,
                HandshakeState::AwaitingSelection,
                HandshakeFrame::Selection {
                    session_id,
                    protocols,
                },
            ) => {
                self.validate_selection(&protocols)?;
                self.config.session_id = session_id;
                self.selected_protocols = protocols;
                self.state = HandshakeState::AwaitingConfirmed;
                Ok(vec![HandshakeOutput::Send(HandshakeFrame::Confirm {
                    session_id,
                })])
            }
            (
                HandshakeRole::Responder,
                HandshakeState::AwaitingConfirmation,
                HandshakeFrame::Confirm { session_id },
            ) => {
                if session_id != self.config.session_id {
                    return Err(self.fail(
                        HandshakeErrorKind::InvalidConfirmation,
                        "session confirmation does not match",
                    ));
                }
                self.state = HandshakeState::Established;
                let session = self.negotiated_session();
                Ok(vec![
                    HandshakeOutput::Send(HandshakeFrame::Confirmed { session_id }),
                    HandshakeOutput::Established(session),
                ])
            }
            (
                HandshakeRole::Initiator,
                HandshakeState::AwaitingConfirmed,
                HandshakeFrame::Confirmed { session_id },
            ) => {
                if session_id != self.config.session_id {
                    return Err(self.fail(
                        HandshakeErrorKind::InvalidConfirmation,
                        "session confirmation does not match",
                    ));
                }
                self.state = HandshakeState::Established;
                Ok(vec![HandshakeOutput::Established(
                    self.negotiated_session(),
                )])
            }
            (_, _, HandshakeFrame::Reject { kind }) => {
                Err(self.fail(kind, "peer rejected handshake"))
            }
            _ => Err(self.fail(
                HandshakeErrorKind::UnexpectedMessage,
                "unexpected handshake message",
            )),
        }
    }

    fn receive_hello(
        &mut self,
        identity: Identity,
        link_versions: VersionRange,
        remote_capabilities: LinkCapabilities,
        protocols: Vec<ProtocolOffer>,
        requested_auth: AuthPath,
    ) -> Result<Vec<HandshakeOutput>, HandshakeError> {
        if protocols.len() > self.config.policy.max_protocol_offers {
            return Err(self.fail(
                HandshakeErrorKind::LimitExceeded,
                "too many protocol offers",
            ));
        }
        let Some(link_version) = self.config.policy.link_versions.negotiate(link_versions) else {
            return Err(self.fail(
                HandshakeErrorKind::IncompatibleVersion,
                "link protocol versions are incompatible",
            ));
        };
        match requested_auth {
            AuthPath::FirstPairing if !self.config.policy.allow_pairing => {
                return Err(self.fail(
                    HandshakeErrorKind::PairingDisabled,
                    "first pairing is disabled",
                ));
            }
            AuthPath::TrustedReconnect
                if !self.config.policy.trusted_peers.contains(&identity.peer_id) =>
            {
                return Err(self.fail(HandshakeErrorKind::PeerNotTrusted, "peer is not trusted"));
            }
            _ => {}
        }
        let local_protocols = match requested_auth {
            AuthPath::FirstPairing => &self.config.policy.pairing_protocols,
            AuthPath::TrustedReconnect => &self.config.policy.protocols,
        };
        let selected = negotiate_protocols(local_protocols, &protocols).map_err(|()| {
            self.fail(
                HandshakeErrorKind::ProtocolConflict,
                "upper protocol identity or schema conflicts",
            )
        })?;
        if selected.is_empty() {
            return Err(self.fail(
                HandshakeErrorKind::NoSharedProtocol,
                "no shared upper protocol",
            ));
        }
        self.remote = Some(identity);
        self.auth_path = Some(requested_auth);
        self.link_version = Some(link_version);
        self.link_capabilities = self
            .config
            .policy
            .link_capabilities
            .intersection(remote_capabilities);
        self.selected_protocols = selected;
        self.state = HandshakeState::AwaitingProof;
        Ok(vec![HandshakeOutput::Send(HandshakeFrame::Challenge {
            responder: self.config.identity,
            link_version,
            link_capabilities: self.link_capabilities,
            auth_path: requested_auth,
            nonce: self.config.challenge_nonce,
        })])
    }

    pub fn decide_identity(
        &mut self,
        decision: ProofDecision,
    ) -> Result<Vec<HandshakeOutput>, HandshakeError> {
        if self.role != HandshakeRole::Responder
            || self.state != HandshakeState::AwaitingVerification
            || self.pending_verification.take().is_none()
        {
            return Err(self.fail(
                HandshakeErrorKind::UnexpectedMessage,
                "identity decision is not expected",
            ));
        }
        if decision == ProofDecision::Reject {
            return Err(self.fail(
                HandshakeErrorKind::IdentityRejected,
                "peer identity was rejected",
            ));
        }
        self.state = HandshakeState::AwaitingConfirmation;
        Ok(vec![HandshakeOutput::Send(HandshakeFrame::Selection {
            session_id: self.config.session_id,
            protocols: self.selected_protocols.clone(),
        })])
    }

    fn validate_selection(&mut self, selected: &[ProtocolSelection]) -> Result<(), HandshakeError> {
        if selected.is_empty() || selected.len() > self.config.policy.max_protocol_offers {
            return Err(self.fail(
                HandshakeErrorKind::NoSharedProtocol,
                "invalid protocol selection",
            ));
        }
        let local_protocols = match self.auth_path {
            Some(AuthPath::FirstPairing) => &self.config.policy.pairing_protocols,
            Some(AuthPath::TrustedReconnect) => &self.config.policy.protocols,
            None => {
                return Err(self.fail(
                    HandshakeErrorKind::UnexpectedMessage,
                    "authentication path is not negotiated",
                ));
            }
        };
        let mut stable_ids = BTreeSet::new();
        for selection in selected {
            if !stable_ids.insert(selection.stable_id) {
                return Err(self.fail(
                    HandshakeErrorKind::ProtocolConflict,
                    "responder selected a protocol more than once",
                ));
            }
            let valid = local_protocols.iter().any(|offer| {
                offer.stable_id == selection.stable_id
                    && offer.schema == selection.schema
                    && offer.capabilities.protocol_id == selection.capabilities.protocol_id
                    && selection.capabilities.is_bounded()
                    && selection.capabilities.is_subset_of(&offer.capabilities)
                    && offer
                        .versions
                        .negotiate(VersionRange::new(selection.version, selection.version))
                        .is_some()
            });
            if !valid {
                return Err(self.fail(
                    HandshakeErrorKind::ProtocolConflict,
                    "responder selected an unsupported protocol",
                ));
            }
        }
        Ok(())
    }

    fn negotiated_session(&self) -> NegotiatedSession {
        NegotiatedSession {
            session_id: self.config.session_id,
            local: self.config.identity,
            remote: self.remote.expect("remote identity negotiated"),
            link_version: self.link_version.expect("link version negotiated"),
            link_capabilities: self.link_capabilities,
            protocols: self.selected_protocols.clone(),
            auth_path: self.auth_path.expect("auth path negotiated"),
        }
    }

    fn fail(&mut self, kind: HandshakeErrorKind, message: &'static str) -> HandshakeError {
        self.state = HandshakeState::Failed;
        HandshakeError::new(kind, message)
    }
}

fn negotiate_protocols(
    local: &[ProtocolOffer],
    remote: &[ProtocolOffer],
) -> Result<Vec<ProtocolSelection>, ()> {
    let mut selected = Vec::new();
    let mut stable_ids = BTreeSet::new();
    for local_offer in local {
        if !stable_ids.insert(local_offer.stable_id) {
            continue;
        }
        if let Some(remote_offer) = remote
            .iter()
            .find(|remote_offer| remote_offer.stable_id == local_offer.stable_id)
        {
            if local_offer.schema != remote_offer.schema
                || (local_offer.debug_identity.is_some()
                    && remote_offer.debug_identity.is_some()
                    && local_offer.debug_identity != remote_offer.debug_identity)
            {
                return Err(());
            }
            if let Some(version) = local_offer.versions.negotiate(remote_offer.versions) {
                let capabilities = local_offer
                    .capabilities
                    .intersect(&remote_offer.capabilities)
                    .ok_or(())?;
                selected.push(ProtocolSelection {
                    stable_id: local_offer.stable_id,
                    version,
                    schema: local_offer.schema,
                    capabilities,
                });
            }
        }
    }
    Ok(selected)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{ConnectionId, EndpointId};

    fn identity(value: u8) -> Identity {
        Identity {
            peer_id: PeerId::from_bytes([value; 32]),
            endpoint_id: EndpointId::from_bytes([value; 16]),
            connection_id: ConnectionId::from_bytes([value; 16]),
        }
    }

    fn offer(namespace: &str) -> ProtocolOffer {
        ProtocolOffer::from_debug_namespace(
            namespace,
            VersionRange::new(ProtocolVersion::new(1, 0), ProtocolVersion::new(1, 2)),
        )
    }

    fn config(value: u8, protocols: Vec<ProtocolOffer>) -> HandshakeConfig {
        HandshakeConfig {
            identity: identity(value),
            policy: HandshakePolicy {
                link_versions: VersionRange::new(
                    ProtocolVersion::new(1, 0),
                    ProtocolVersion::new(1, 1),
                ),
                link_capabilities: LinkCapabilities::COMPACT_CHANNEL_ID
                    | LinkCapabilities::DATAGRAMS
                    | LinkCapabilities::TYPED_CONTROL,
                pairing_protocols: protocols.clone(),
                protocols,
                allow_pairing: true,
                trusted_peers: BTreeSet::new(),
                max_protocol_offers: 8,
                max_identity_proof_bytes: 64,
            },
            challenge_nonce: [value; 32],
            identity_proof: IdentityProof {
                opaque: vec![value; 8],
            },
            session_id: SessionId::from_bytes([value; 16]),
        }
    }

    fn sent(outputs: Vec<HandshakeOutput>) -> HandshakeFrame {
        outputs
            .into_iter()
            .find_map(|output| match output {
                HandshakeOutput::Send(frame) => Some(frame),
                _ => None,
            })
            .expect("send output")
    }

    #[test]
    fn pairing_handshake_negotiates_multiple_namespaces() {
        let protocols = vec![offer("mutsuki.lilia"), offer("mutsuki.distributed")];
        let mut initiator = HandshakeMachine::initiator(config(1, protocols.clone()));
        let mut responder = HandshakeMachine::responder(config(2, protocols));

        let hello = initiator.start(AuthPath::FirstPairing).unwrap();
        let challenge = sent(responder.receive(hello).unwrap());
        let proof = sent(initiator.receive(challenge).unwrap());
        let verification = responder.receive(proof).unwrap();
        assert!(matches!(
            &verification[0],
            HandshakeOutput::VerifyIdentity(request)
                if request.auth_path == AuthPath::FirstPairing
        ));
        let selection = sent(responder.decide_identity(ProofDecision::Accept).unwrap());
        let confirmation = sent(initiator.receive(selection).unwrap());
        let responder_outputs = responder.receive(confirmation).unwrap();
        let confirmed = sent(responder_outputs.clone());
        assert!(responder_outputs.iter().any(|output| matches!(
            output,
            HandshakeOutput::Established(session) if session.protocols.len() == 2
        )));
        let initiator_outputs = initiator.receive(confirmed).unwrap();
        assert!(matches!(
            &initiator_outputs[0],
            HandshakeOutput::Established(session)
                if session.protocols.len() == 2
                    && session.control_identity_mode() == crate::ControlIdentityMode::TypedV1
        ));
        assert_eq!(initiator.state(), HandshakeState::Established);
        assert_eq!(responder.state(), HandshakeState::Established);
    }

    #[test]
    fn trusted_reconnect_rejects_unknown_peer() {
        let mut initiator = HandshakeMachine::initiator(config(1, vec![offer("test")]));
        let mut responder = HandshakeMachine::responder(config(2, vec![offer("test")]));
        let hello = initiator.start(AuthPath::TrustedReconnect).unwrap();
        let error = responder.receive(hello).unwrap_err();
        assert_eq!(error.kind, HandshakeErrorKind::PeerNotTrusted);
        assert_eq!(responder.state(), HandshakeState::Failed);
    }

    #[test]
    fn first_pairing_does_not_advertise_sensitive_protocols() {
        let mut config = config(1, vec![offer("mutsuki.sensitive")]);
        config.policy.pairing_protocols = vec![offer("mutsuki.link.pairing")];
        let mut initiator = HandshakeMachine::initiator(config);
        let hello = initiator.start(AuthPath::FirstPairing).unwrap();
        assert!(matches!(
            hello,
            HandshakeFrame::Hello { protocols, .. }
                if protocols.len() == 1
                    && protocols[0].debug_identity.as_ref().map(|identity| identity.name.as_str())
                        == Some("pairing")
        ));
    }

    #[test]
    fn initiator_rejects_responder_capability_escalation() {
        let mut initiator = HandshakeMachine::initiator(config(1, vec![offer("test")]));
        initiator.start(AuthPath::FirstPairing).unwrap();
        let error = initiator
            .receive(HandshakeFrame::Challenge {
                responder: identity(2),
                link_version: ProtocolVersion::new(1, 1),
                link_capabilities: LinkCapabilities::from_bits(u64::MAX),
                auth_path: AuthPath::FirstPairing,
                nonce: [2; 32],
            })
            .unwrap_err();
        assert_eq!(error.kind, HandshakeErrorKind::IncompatibleVersion);
        assert_eq!(initiator.state(), HandshakeState::Failed);
    }

    #[test]
    fn handshake_rejects_protocol_capability_escalation() {
        let local_offer = offer("test");
        let stable_id = local_offer.stable_id;
        let schema = local_offer.schema;
        let mut initiator = HandshakeMachine::initiator(config(1, vec![local_offer]));
        initiator.start(AuthPath::FirstPairing).unwrap();
        initiator
            .receive(HandshakeFrame::Challenge {
                responder: identity(2),
                link_version: ProtocolVersion::new(1, 1),
                link_capabilities: LinkCapabilities::TYPED_CONTROL,
                auth_path: AuthPath::FirstPairing,
                nonce: [2; 32],
            })
            .unwrap();
        let error = initiator
            .receive(HandshakeFrame::Selection {
                session_id: SessionId::from_bytes([2; 16]),
                protocols: vec![ProtocolSelection {
                    stable_id,
                    version: ProtocolVersion::new(1, 1),
                    schema,
                    capabilities: ProtocolCapabilitySet {
                        protocol_id: stable_id,
                        words: vec![1],
                    },
                }],
            })
            .unwrap_err();
        assert_eq!(error.kind, HandshakeErrorKind::ProtocolConflict);
    }
}
